# Generated by Django 2.2.5 on 2019-10-06 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, unique=True, verbose_name='Question Text')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Question Description')),
                ('asked_on', models.DateTimeField(auto_now_add=True, verbose_name='Asked on ')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('topic', models.ManyToManyField(to='Forum.Topic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Question Author')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10000, verbose_name='Answer')),
                ('answered_on', models.DateTimeField(auto_now_add=True, verbose_name='Answered on ')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Forum_question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Comment')),
                ('commented_on', models.DateTimeField(auto_now_add=True, verbose_name='Asked on ')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('upvotes', models.IntegerField(default=0, verbose_name='Upvotes')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.Forum_answer', verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
